package com.ecnu.car_rent.dao;

import com.ecnu.car_rent.model.CarOrder;

public interface CarOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int deleteByPrimaryKey(Integer carOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insert(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insertSelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    CarOrder selectByPrimaryKey(Integer carOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeySelective(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CarOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKey(CarOrder record);
}