package com.ecnu.car_rent.dao;

import com.ecnu.car_rent.model.Massage;

public interface MassageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int deleteByPrimaryKey(Integer massageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insert(Massage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insertSelective(Massage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    Massage selectByPrimaryKey(Integer massageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeySelective(Massage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Massage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table massage
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKey(Massage record);
}