package com.ecnu.car_rent.dao;

import com.ecnu.car_rent.model.StopOrder;

public interface StopOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int deleteByPrimaryKey(Integer stopOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insert(StopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int insertSelective(StopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    StopOrder selectByPrimaryKey(Integer stopOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeySelective(StopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(StopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    int updateByPrimaryKey(StopOrder record);
}