package com.ecnu.car_rent.model;

public class StopOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_order.stop_order_id
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    private Integer stopOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_order.get_name
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    private String getName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_order.money
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_order.address
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stop_order.description
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public StopOrder(Integer stopOrderId, String getName, Integer money, String address, String description) {
        this.stopOrderId = stopOrderId;
        this.getName = getName;
        this.money = money;
        this.address = address;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stop_order
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public StopOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_order.stop_order_id
     *
     * @return the value of stop_order.stop_order_id
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public Integer getStopOrderId() {
        return stopOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_order.stop_order_id
     *
     * @param stopOrderId the value for stop_order.stop_order_id
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public void setStopOrderId(Integer stopOrderId) {
        this.stopOrderId = stopOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_order.get_name
     *
     * @return the value of stop_order.get_name
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public String getGetName() {
        return getName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_order.get_name
     *
     * @param getName the value for stop_order.get_name
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public void setGetName(String getName) {
        this.getName = getName == null ? null : getName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_order.money
     *
     * @return the value of stop_order.money
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_order.money
     *
     * @param money the value for stop_order.money
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_order.address
     *
     * @return the value of stop_order.address
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_order.address
     *
     * @param address the value for stop_order.address
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stop_order.description
     *
     * @return the value of stop_order.description
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stop_order.description
     *
     * @param description the value for stop_order.description
     *
     * @mbggenerated Sun Dec 17 14:36:13 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}